### ISSUE TITLE
TypeError: window.customElements is undefined

### ISSUE THREAD

**Issue by rianby64** [m3co/pseudoimport-html#34]
https://sentry.io/3-constructora-sas/pseudimport-html/issues/207954648/

```
TypeError: window.customElements is undefined
  at None (/src/fragment-ce.js:160:3)
  at None (/src/fragment-ce.js:1:1)
```

**Comment by rianby64** [comment]
Add the correct polyfill that brings up ```customElement.define``` to browser.

**Comment by rianby64** [comment]
As per #32 and #42 ```customElement``` is intended to be used under ES6 and new browsers...
